name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest src/tests/test_example_agent.py

      - name: Build application
        run: |
          python setup.py sdist bdist_wheel

      - name: Deploy
        run: |
          echo "Deploying application..."
          # Add deployment commands here
          # e.g., scp, rsync, or any deployment script
          
      - name: Notify success
        run: |
          echo "Deployment successful!"